version: "3"

volumes:
  node_modules:
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
