# syntax = docker/dockerfile:1

ARG NODE_VERSION=20.10.0

FROM node:${NODE_VERSION}-slim as base

ENV NODE_ENV=development

WORKDIR /src

# Build

FROM base as build

COPY --link package.json pnpm-lock.yaml .
RUN npm install -g pnpm
RUN pnpm install

# Run

FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]
