# fly.toml app configuration file generated for jobsearch-app on 2024-06-07T11:03:02+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobsearch-app'
primary_region = 'bos'

[build]

[env]
NUXT_CLIENT_URL = 'https://jobsearch.nirjan.net'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
