# fly.toml app configuration file generated for jobsearch-frontend on 2024-03-11T11:24:54+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobsearch-frontend'
primary_region = 'bos'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
